version: '3.8'

services:
  go_app:
    build: .
    container_name: go_app
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - go_app
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email wonderrfau1tl@gmail.com --agree-tos --no-eff-email --staging -d example.com && certbot renew --dry-run"

networks:
  app_network:
    driver: bridge
